name: cse530
channels: !!python/tuple
- bioconda
- r
- defaults
- conda-forge
dependencies:
- fabric3=1.13.1.post1=py36_0
- paramiko=1.18.1=py36_0
- bleach=1.5.0=py36_0
- decorator=4.0.11=py36_0
- ecdsa=0.13=py36_0
- entrypoints=0.2.2=py36_1
- html5lib=0.999=py36_0
- ipykernel=4.5.2=py36_0
- ipython=5.3.0=py36_0
- ipython_genutils=0.1.0=py36_0
- jinja2=2.9.5=py36_0
- jsonschema=2.5.1=py36_0
- jupyter_client=5.0.0=py36_0
- jupyter_core=4.3.0=py36_0
- libpq=9.5.4=0
- libsodium=1.0.10=0
- markupsafe=0.23=py36_2
- mistune=0.7.4=py36_0
- mkl=2017.0.1=0
- nbconvert=5.1.1=py36_0
- nbformat=4.3.0=py36_0
- notebook=4.4.1=py36_0
- numpy=1.12.1=py36_0
- openssl=1.0.2k=1
- pandas=0.19.2=np112py36_1
- pandocfilters=1.4.1=py36_0
- path.py=10.1=py36_0
- pexpect=4.2.1=py36_0
- pickleshare=0.7.4=py36_0
- pip=9.0.1=py36_1
- prompt_toolkit=1.0.13=py36_0
- psycopg2=2.7.1=py36_0
- ptyprocess=0.5.1=py36_0
- pycrypto=2.6.1=py36_4
- pygments=2.2.0=py36_0
- python=3.6.0=0
- python-dateutil=2.6.0=py36_0
- pytz=2016.10=py36_0
- pyzmq=16.0.2=py36_0
- readline=6.2=2
- setuptools=27.2.0=py36_0
- simplegeneric=0.8.1=py36_1
- six=1.10.0=py36_0
- sqlite=3.13.0=0
- terminado=0.6=py36_0
- testpath=0.3=py36_0
- tk=8.5.18=0
- tornado=4.4.2=py36_0
- traitlets=4.3.2=py36_0
- wcwidth=0.1.7=py36_0
- wheel=0.29.0=py36_0
- xz=5.2.2=1
- zeromq=4.1.5=0
- zlib=1.2.8=3
- pip:
  - ipython-genutils==0.1.0
  - jupyter-client==5.0.0
  - jupyter-core==4.3.0
  - pgcopy==1.1.0
  - prompt-toolkit==1.0.13
  - psycopg2==2.7.1
